### ISSUE TITLE
java.net.SocketException: Unexpected end of file from server when sending test message to an unknown AS2 ID

### ISSUE THREAD

**Issue by jochenberger** [phax/as2-server#16]
If i modify the test client to send the test message to "OpenAS2X" instead of "OpenAS2B", I get
```
[2015-10-15T15:39:38,708] [AS2-SERVER] [INFO ] [main] Submitting message [<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>] -- com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:678)
[2015-10-15T15:39:38,756] [AS2-SERVER] [INFO ] [main] Connecting to http://localhost:10080/HttpReceiver [<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>] -- com.helger.as2lib.processor.sender.AS2SenderModule._sendViaHTTP(AS2SenderModule.java:608)
[2015-10-15T15:39:38,796] [AS2-SERVER] [INFO ] [main] transferred 2775 bytes in 0.031 seconds at 87.428 KBps [<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>] -- com.helger.as2lib.processor.sender.AS2SenderModule._sendViaHTTP(AS2SenderModule.java:621)
[2015-10-15T15:39:38,829] [AS2-SERVER] [INFO ] [main] OpenAS2Exception terminated: java.net.SocketException: Unexpected end of file from server; sources: {message=[AS2Message@0x198b6731: data=javax.mail.internet.MimeBodyPart@7c6908d7; MDN=null]} -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:111)
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792) ~[?:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789) ~[?:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535) ~[?:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_66-internal]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_66-internal]
	at com.helger.as2lib.processor.sender.AS2SenderModule._sendViaHTTP(AS2SenderModule.java:624) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:698) [as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:295) [as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2.test.MainTestClient.main(MainTestClient.java:125) [test-classes/:?]
[2015-10-15T15:39:38,834] [AS2-SERVER] [INFO ] [main] Retry count exceeded - no more retries for [<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>] -- com.helger.as2lib.processor.sender.AbstractSenderModule.doResend(AbstractSenderModule.java:120)
[2015-10-15T15:39:38,834] [AS2-SERVER] [ERROR] [main] Error sending AS2 message -- com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:304)
com.helger.as2lib.exception.WrappedOpenAS2Exception: java.net.SocketException: Unexpected end of file from server
	at com.helger.as2lib.exception.WrappedOpenAS2Exception.wrap(WrappedOpenAS2Exception.java:66) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:711) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:295) [as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2.test.MainTestClient.main(MainTestClient.java:125) [test-classes/:?]
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792) ~[?:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789) ~[?:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535) ~[?:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_66-internal]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_66-internal]
	at com.helger.as2lib.processor.sender.AS2SenderModule._sendViaHTTP(AS2SenderModule.java:624) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:698) ~[as2-lib-2.2.1.jar:2.2.1]
	... 2 more
```
The server logs look like this:
```
[2015-10-15T15:39:26,298] [AS2-SERVER] [INFO ] [main] ph-OpenAS2 v2.2.1 - starting Server... -- com.helger.as2.app.MainOpenAS2Server.start(MainOpenAS2Server.java:67)
[2015-10-15T15:39:26,300] [AS2-SERVER] [INFO ] [main] Loading configuration... -- com.helger.as2.app.MainOpenAS2Server.start(MainOpenAS2Server.java:72)
[2015-10-15T15:39:26,386] [AS2-SERVER] [INFO ] [main]   loading certificates -- com.helger.as2.app.session.AS2ServerXMLSession.loadCertificates(AS2ServerXMLSession.java:117)
[2015-10-15T15:39:26,700] [AS2-SERVER] [INFO ] [main]   loading partnerships -- com.helger.as2.app.session.AS2ServerXMLSession.loadPartnerships(AS2ServerXMLSession.java:156)
[2015-10-15T15:39:26,709] [AS2-SERVER] [INFO ] [main]   loading commands -- com.helger.as2.app.session.AS2ServerXMLSession.loadCommands(AS2ServerXMLSession.java:127)
[2015-10-15T15:39:26,718] [AS2-SERVER] [INFO ] [main]   loading 2 command processors -- com.helger.as2.app.session.AS2ServerXMLSession.loadCommandProcessors(AS2ServerXMLSession.java:138)
[2015-10-15T15:39:26,719] [AS2-SERVER] [INFO ] [main]     loaded command processor StreamCommandProcessor -- com.helger.as2.app.session.AS2ServerXMLSession.loadCommandProcessor(AS2ServerXMLSession.java:151)
[2015-10-15T15:39:26,831] [AS2-SERVER] [INFO ] [main]     loaded command processor SocketCommandProcessor -- com.helger.as2.app.session.AS2ServerXMLSession.loadCommandProcessor(AS2ServerXMLSession.java:151)
[2015-10-15T15:39:26,831] [AS2-SERVER] [INFO ] [main]   loading message processor -- com.helger.as2.app.session.AS2ServerXMLSession.loadMessageProcessor(AS2ServerXMLSession.java:166)
[2015-10-15T15:39:26,837] [AS2-SERVER] [INFO ] [main]     loaded processor module AS2SenderModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,840] [AS2-SERVER] [INFO ] [main]     loaded processor module AS2DirectoryPollingModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,840] [AS2-SERVER] [INFO ] [main]     loaded processor module AS2DirectoryPollingModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,840] [AS2-SERVER] [INFO ] [main]     loaded processor module AS2DirectoryPollingModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,842] [AS2-SERVER] [INFO ] [main]     loaded processor module MDNFileModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,842] [AS2-SERVER] [INFO ] [main]     loaded processor module MessageFileModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,843] [AS2-SERVER] [INFO ] [main]     loaded processor module AS2ReceiverModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,844] [AS2-SERVER] [INFO ] [main]     loaded processor module AS2MDNReceiverModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,845] [AS2-SERVER] [INFO ] [main]     loaded processor module DirectoryResenderModule -- com.helger.as2.app.session.AS2ServerXMLSession.loadProcessorModule(AS2ServerXMLSession.java:185)
[2015-10-15T15:39:26,845] [AS2-SERVER] [INFO ] [main] Starting Active Modules... -- com.helger.as2.app.MainOpenAS2Server.start(MainOpenAS2Server.java:84)
[2015-10-15T15:39:26,846] [AS2-SERVER] [INFO ] [main] Inited AS2MainThread-AS2ReceiverModule at 0.0.0.0/0.0.0.0:10080 -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$MainThread.<init>(AbstractActiveNetModule.java:263)
[2015-10-15T15:39:26,847] [AS2-SERVER] [INFO ] [AS2MainThread-AS2ReceiverModule] AS2MainThread: run -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$MainThread.run(AbstractActiveNetModule.java:277)
[2015-10-15T15:39:26,847] [AS2-SERVER] [INFO ] [main] Inited AS2MainThread-AS2MDNReceiverModule at 0.0.0.0/0.0.0.0:10081 -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$MainThread.<init>(AbstractActiveNetModule.java:263)
[2015-10-15T15:39:26,847] [AS2-SERVER] [INFO ] [AS2MainThread-AS2MDNReceiverModule] AS2MainThread: run -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$MainThread.run(AbstractActiveNetModule.java:277)
[2015-10-15T15:39:26,847] [AS2-SERVER] [INFO ] [main] Loading Command Processor com.helger.as2.cmdprocessor.StreamCommandProcessor -- com.helger.as2.app.MainOpenAS2Server.start(MainOpenAS2Server.java:91)
[2015-10-15T15:39:26,847] [AS2-SERVER] [INFO ] [main] Loading Command Processor com.helger.as2.cmdprocessor.SocketCommandProcessor -- com.helger.as2.app.MainOpenAS2Server.start(MainOpenAS2Server.java:91)
[2015-10-15T15:39:26,848] [AS2-SERVER] [INFO ] [main] OpenAS2 Started -- com.helger.as2.app.MainOpenAS2Server.start(MainOpenAS2Server.java:98)
[2015-10-15T15:39:38,761] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] AS2ConnectionThread: run -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:226)
[2015-10-15T15:39:38,763] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] Incoming connection 127.0.0.1:39498 -- com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:538)
[2015-10-15T15:39:38,798] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] received 2775 bytes in 0.029 seconds at 93.458 KBps from 127.0.0.1:39498 [<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>] -- com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:562)
[2015-10-15T15:39:38,817] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] OpenAS2Exception terminated: Partnership not found: [Partnership@0x2b18c184: name=auto-created-dummy; senderIDs=[StringMap@0x5d20d32e: attrs={as2_id=OpenAS2X}]; receiverIDs=[StringMap@0x11c9d866: attrs={as2_id=OpenAS2A}]; attributes=[StringMap@0x101ad046: attrs={}]]; sources: {message=[AS2Message@0x7d632720: data=javax.mail.internet.MimeBodyPart@26013201; MDN=[[AS2MessageMDN@0x79d4c44f: attributes=[StringMap@0x3f8ab3d3: attrs={}]; headers=javax.mail.internet.InternetHeaders@5bb4d925; partnership=[Partnership@0x2b18c184: name=auto-created-dummy; senderIDs=[StringMap@0x5d20d32e: attrs={as2_id=OpenAS2X}]; receiverIDs=[StringMap@0x11c9d866: attrs={as2_id=OpenAS2A}]; attributes=[StringMap@0x101ad046: attrs={}]]]; message=<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>; data=null; text=null]]} -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:111)
[2015-10-15T15:39:38,818] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] OpenAS2Exception terminated: automatic-action/MDN-sent-automatically; processed/Error:authentication-failed; sources: {message=[AS2Message@0x7d632720: data=javax.mail.internet.MimeBodyPart@26013201; MDN=[[AS2MessageMDN@0x79d4c44f: attributes=[StringMap@0x3f8ab3d3: attrs={}]; headers=javax.mail.internet.InternetHeaders@5bb4d925; partnership=[Partnership@0x2b18c184: name=auto-created-dummy; senderIDs=[StringMap@0x5d20d32e: attrs={as2_id=OpenAS2X}]; receiverIDs=[StringMap@0x11c9d866: attrs={as2_id=OpenAS2A}]; attributes=[StringMap@0x101ad046: attrs={}]]]; message=<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>; data=null; text=null]]} -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:111)
com.helger.as2lib.partner.PartnershipNotFoundException: Partnership not found: [Partnership@0x26864f06: name=auto-created-dummy; senderIDs=[StringMap@0x58a9c361: attrs={as2_id=OpenAS2A}]; receiverIDs=[StringMap@0x670bcb9d: attrs={as2_id=OpenAS2X}]; attributes=[StringMap@0x06cd501f: attrs={}]]
	at com.helger.as2lib.partner.AbstractPartnershipFactory.getPartnership(AbstractPartnershipFactory.java:103) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.partner.AbstractPartnershipFactory.updatePartnership(AbstractPartnershipFactory.java:223) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handleIncomingMessage(AS2ReceiverHandler.java:384) [as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:568) [as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:228) [as2-lib-2.2.1.jar:2.2.1]
[2015-10-15T15:39:38,823] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] OpenAS2Exception terminated: Stored invalid message to /home/jochen/git/upstream/as2-server/data/inbox/error/OpenAS2A, OpenAS2X, _ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X_ -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:111)
[2015-10-15T15:39:38,824] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] AS2ConnectionThread: done running -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:240)
[2015-10-15T15:39:38,824] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] AS2ConnectionThread: run -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:226)
[2015-10-15T15:39:38,824] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] Incoming connection 127.0.0.1:39500 -- com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:538)
[2015-10-15T15:39:38,825] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] received 2775 bytes in 0.0 seconds at 2.727 KBps from 127.0.0.1:39500 [<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>] -- com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:562)
[2015-10-15T15:39:38,826] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] OpenAS2Exception terminated: Partnership not found: [Partnership@0x19387ddf: name=auto-created-dummy; senderIDs=[StringMap@0x304b50f5: attrs={as2_id=OpenAS2X}]; receiverIDs=[StringMap@0x6199455a: attrs={as2_id=OpenAS2A}]; attributes=[StringMap@0x612fc98d: attrs={}]]; sources: {message=[AS2Message@0x3b2386f2: data=javax.mail.internet.MimeBodyPart@5105b59b; MDN=[[AS2MessageMDN@0x7a9d8974: attributes=[StringMap@0x6561540b: attrs={}]; headers=javax.mail.internet.InternetHeaders@42525a43; partnership=[Partnership@0x19387ddf: name=auto-created-dummy; senderIDs=[StringMap@0x304b50f5: attrs={as2_id=OpenAS2X}]; receiverIDs=[StringMap@0x6199455a: attrs={as2_id=OpenAS2A}]; attributes=[StringMap@0x612fc98d: attrs={}]]]; message=<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>; data=null; text=null]]} -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:111)
[2015-10-15T15:39:38,826] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] OpenAS2Exception terminated: automatic-action/MDN-sent-automatically; processed/Error:authentication-failed; sources: {message=[AS2Message@0x3b2386f2: data=javax.mail.internet.MimeBodyPart@5105b59b; MDN=[[AS2MessageMDN@0x7a9d8974: attributes=[StringMap@0x6561540b: attrs={}]; headers=javax.mail.internet.InternetHeaders@42525a43; partnership=[Partnership@0x19387ddf: name=auto-created-dummy; senderIDs=[StringMap@0x304b50f5: attrs={as2_id=OpenAS2X}]; receiverIDs=[StringMap@0x6199455a: attrs={as2_id=OpenAS2A}]; attributes=[StringMap@0x612fc98d: attrs={}]]]; message=<ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X>; data=null; text=null]]} -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:111)
com.helger.as2lib.partner.PartnershipNotFoundException: Partnership not found: [Partnership@0x4efadb56: name=auto-created-dummy; senderIDs=[StringMap@0x403d3cf9: attrs={as2_id=OpenAS2A}]; receiverIDs=[StringMap@0x4402b026: attrs={as2_id=OpenAS2X}]; attributes=[StringMap@0x010036c2: attrs={}]]
	at com.helger.as2lib.partner.AbstractPartnershipFactory.getPartnership(AbstractPartnershipFactory.java:103) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.partner.AbstractPartnershipFactory.updatePartnership(AbstractPartnershipFactory.java:223) ~[as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handleIncomingMessage(AS2ReceiverHandler.java:384) [as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:568) [as2-lib-2.2.1.jar:2.2.1]
	at com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:228) [as2-lib-2.2.1.jar:2.2.1]
[2015-10-15T15:39:38,826] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] OpenAS2Exception terminated: Stored invalid message to /home/jochen/git/upstream/as2-server/data/inbox/error/OpenAS2A, OpenAS2X, _ph-OpenAS2-15102015153938+0200-7946@OpenAS2A_OpenAS2X_.0 -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:111)
[2015-10-15T15:39:38,827] [AS2-SERVER] [INFO ] [AS2ConnectionThread-AS2ReceiverModule] AS2ConnectionThread: done running -- com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:240)
```

**Comment by phax** [comment]
Does this happen only at this error type or always?

**Comment by jochenberger** [comment]
I'm not sure what you mean. It doesn't happen if the message configuration matches the configured partnerships.

**Comment by phax** [comment]
That's not what I meant. Sorry for being imprecise. Do you know whether the client always has this parsing problem if the server throws an exception. The planned outcome would be, that the server delivers a negative MDN and the client can interprete this :)

**Comment by jochenberger** [comment]
Yes, I'd also expect that behavior. But I don't know if that's always the case. At least some exceptions lead to a connection timeout (e.g. if I return `null` from `AS2ReceiverModule.createHandler` or throw a `RuntimeException` from `AS2ReceiverModule.handleIncomingMessage`).

**Comment by phax** [comment]
The funny thing is: the MDN is not send back, because a "PartnershipNotFoundException" happens when creating an MDN for the original "PartnershipNotFoundException" :)
